// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace roadcap.recipies.entities.Models
{
    [Table("recipe")]
    public partial class Recipe
    {
        public Recipe()
        {
            Ingredients = new HashSet<Ingredient>();
        }

        [Key]
        [Column("recipe_id")]
        public int RecipeId { get; set; }

        [Required]
        [Column("title")]
        [StringLength(50)]
        public string Title { get; set; }

        [Column("image")]
        public byte[] Image { get; set; }

        [Required]
        [Column("instructions")]
        public string Instructions { get; set; }

        [InverseProperty(nameof(Ingredient.Recipe))]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}